[package]
name = "asr_rs"
version = "0.1.0"
edition = "2024"

[features]
model_download=["dep:indicatif", "dep:ureq"]
no_model_log=[]
cuda=["whisper-rs/cuda"]
vulkan=["whisper-rs/vulkan"]
tui=["dep:ratatui", "dep:cpal", "dep:anyhow"]
async=["dep:tokio"]
default=["model_download", "async", "tui"]

[dependencies]
colored = "3.1.1"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
whisper-rs = {version="0.15.1"}
cpal = {version="0.17.1",optional=true}
indicatif = {version="0.18.4",optional=true}
ureq = { version = "3.2.0", optional = true }
ratatui = { version ="0.30.0", optional = true }
tokio = { version = "1.49.0", features = ["sync"], optional = true }
anyhow = { version = "1.0.102", optional = true}

[[bin]]
name = "asr_rs"
required-features = ["tui"]
